#include "StaticMurmur.hpp"

int main()
{
	// User has to provide a seed for the algorithm, in this case 123321u.
	constexpr auto hash = murmur::static_hash_x86_32("hellopleasework", 123321u);
	// the constant has been generated by Austion Appleby's version,
	// with the same string and hash.
	static_assert(hash == 3269627231, "Something is wrong with the Murmur3 implementation");
	return hash;
}
